### ISSUE TITLE
dev-master is required for v2.2.5

### ISSUE THREAD

**Issue by U4I-Deryk-Hopley** [MovingImage24/VMProApiClient#73]
In composer.json for video-manager-meta requires dev-master instead of a specific version like 2.1.0.
This is a risk in our production environment. Can this be updated?

"movingimage/video-manager-meta": "dev-master"

Thank you

**Comment by robertszeker** [comment]
@Deryk-U4I I released a new version 2.2.6 without dev-master dependency

**Comment by U4I-Deryk-Hopley** [comment]
Perfect. Thank you very much.
